### PR TITLE
Milestone4

### PR DESCRIPTION
**Pull request by logankimbs**
fixed bug that prevented user from seeing letters when typing. added colors to keyboard

### CODE REVIEW

**Comment by SpencerKing7** [comment]
Hey Logan can you check to make sure that the keyboard colors will update with the state of the guesses? For example, if a correct letter is guessed in the wrong spot it is yellow but once it is in the correct spot the keyboard stays yellow but needs to turn green.

**Comment by logankimbs** [comment]
@SpencerKing7 the instructions on this are confusing. He makes it sounds like once the key color is changed to not ever change it which is how I set it up. Am I understanding the instructions correctly?

**Comment by SpencerKing7** [comment]
@logankimbs I think they are supposed to change as the guess is made correctly... @abbieluper can you confirm this?

**Comment by abbieluper** [comment]
Yes I think @SpencerKing7 is correct because that is how the actual game of Wordle is played...but the instructions are worded weird.

**Comment by abbieluper** [comment]
I will try to ask around

**Comment by logankimbs** [comment]
Okay should be good to go

**Review by abbieluper — APPROVED** [review]
Looks good! Thx!

**Review by abbieluper — APPROVED** [review]
looks good!

**Review by SpencerKing7 — APPROVED** [review]

**Pull request merged**
